### ISSUE TITLE
Fix dependencies

### ISSUE THREAD

**Issue by aitormagan** [requests/requests-oauthlib#157]
Each time the `oauthlib` library is changed, I have to change my code because the behaviour changes. So, can you fix the version of the libraries that you use?
At least you should fix the mayor number of the dependencies since when this number changes, the API often changes.

**Comment by freeauto** [comment]
+1

**Comment by akshar-raaj** [comment]
In case somebody is still facing this issue, you can add os.environ['OAUTHLIB_RELAX_TOKEN_SCOPE'] = "1". I am not sure if this is the best solution, but it was a quick fix which worked for me.

**Comment by altryne** [comment]
Guys I'm still hitting this issue as well!

**Comment by singingwolfboy** [comment]
It appears that this issue was resolved a few years ago with the release of oauthlib 0.8.0. If the dependencies are still a problem for this project, please reopen this issue, or file a new issue and refer to this one.

**Comment by nbveeresh1995** [comment]
Thank you @benjaminwhite, 👍
