### ISSUE TITLE
Create end to end tests for common providers

### ISSUE THREAD

**Issue by ib-lundgren** [requests/requests-oauthlib#160]
These tests should be automated but could be excluded from the standard suite if there is no good way to hide real client ids and secrets in a test setup such as travis.

A good start would be for Google, Twitter and Facebook.

Ideally this should further help making new releases smoother. cc https://github.com/requests/requests-oauthlib/issues/157

**Comment by JonathanHuot** [comment]
Closed as part of the 1.4.0 release https://github.com/requests/requests-oauthlib/pull/530
I'm suggesting to open a new MR for each "common providers" when working on it.
