### ISSUE TITLE
Should expires_at be expires_in in example?

### ISSUE THREAD

**Issue by robmoore** [requests/requests-oauthlib#162]
In the [example](https://github.com/requests/requests-authlib/blob/master/docs/examples/real_world_example_with_refresh.rst) application showing the refresh token flow, there is a reference to `expires_at`: `token['expires_at'] = time() - 10`.
I suspect this should actually be `expires_in` instead.

**Comment by duaneking** [comment]
There is some confusion here about the nature of `expires_at` verses `expires_in`.

But that link doesn't exist when I go to it..
