### ISSUE TITLE
Compatability with latest version of oauthlib

### ISSUE THREAD

**Issue by HEdingfield** [requests/requests-oauthlib#186]
v1.0.0 was released the other day (and v1.0.1 just came out yesterday). It looks like there are a few "breaking changes"; it's probably a good idea to check over all this to make sure is fully compatible with the new version: https://github.com/idan/oauthlib/releases

**Comment by Lukasa** [comment]
Agreed. It'll be interesting to see when we can get the manpower to do that, though.

**Comment by cxong** [comment]
fwiw I've tested locally with oauthlib 1.0.3 and all the tests pass.

**Comment by singingwolfboy** [comment]
It's now February 2016. I'm guessing this issue can be closed.
