### ISSUE TITLE
Documentation Problem in Real World Example

### ISSUE THREAD

**Issue by hellerve** [requests/requests-oauthlib#199]
Hey,

in the [real world example](https://github.com/requests/requests-oauthlib/blob/master/docs/examples/real_world_example.rst) you are using Githubs API as a case study and Flask as the framework. It would probably be worth a mention that with Github's API, the `redirect_uri` parameter is optional, especially if you are using flask on the other side, as `flask-oauthlib` will require this parameter and if users want to create something based on that example, this will probably be a minor pitfall.

I can issue a PR to fix this if you agree that this is somewhat confusing.

Cheers

**Comment by Lukasa** [comment]
I'd be happy to accept a PR that puts that information in a `.. note:` block.
