### ISSUE TITLE
Twitter Api: getting user off 

### ISSUE THREAD

**Issue by jmgamboa** [requests/requests-oauthlib#210]
Hello everyone! excited to see an active auth library in python that supports oauth1. What is the difference between this and rauth.  What I am trying to do is get the user given their access token and secret.  I have a user authenticating for twitter via mobile. They are passing back the token and secret. On the back end, I would like to see which user is tied to those keys.

**Comment by sigmavirus24** [comment]
@jmgamboa the issue tracker is not a Q&A section. If you have specific code you're using, you should post your questions on how to retrieve Twitter users to [StackOverflow](https://stackoverflow.com)
