### ISSUE TITLE
v0.6.0 seems to break oddly for LinkedIn

### ISSUE THREAD

**Issue by wezzynl** [requests/requests-oauthlib#221]
When using v0.5.0 and fetching an Access Token from LinkedIn this works as expected. When we upgrade to v0.6.0 however, the fetching succeeds but the Access Token starts out as invalid. It can take up to 4 minutes before the LinkedIn API accepts the Access Token as valid. During that time an exception like this gets thrown:

```
Exception: {
  "errorCode": 0,
  "message": "Unable to verify access token",
  "requestId": "L595QANTTL",
  "status": 401,
  "timestamp": 1454600867781
}
```

Like said, after up to 4 minutes that very same Access Token starts to work. Of course this is a problem as you can't really login a user in your own implementation that way. Please note that this seems to only take place when you are logged _out_ of www.linkedin.com - so when the OAuth Dialog first asks you to log in to your LinkedIn account. When you are already logged in and it just flies through the OAuth2 dialog it works (most of the time).

We've diffed version v0.5.0 against v0.6.0 and what seems to be causing it is a line in oauth2_session.py at line number 200:

```
auth = auth or requests.auth.HTTPBasicAuth(username, password)
```

When I comment out that line, all starts to work correctly for LinkedIn, so it seems that it's adding BasicAuth headers with empty username and password and that in turn seems to get LinkedIn upset, where it refuses to allow immediate access to the API even though they provided an actual Access Token.

**Comment by wezzynl** [comment]
Ah... Refs #218  :)

**Comment by Lukasa** [comment]
Yeah, looks like we need to make sure we have an appropriate compliance fix for LinkedIn as well.

**Comment by singingwolfboy** [comment]
It looks like [requests-oauthlib now has a compliance fix for LinkedIn](https://github.com/singingwolfboy/requests-oauthlib/blob/master/requests_oauthlib/compliance_fixes/linkedin.py), so I'm closing this issue.
