### ISSUE TITLE
Different behavior between localhost and staging server

### ISSUE THREAD

**Issue by jakeemerson** [requests/requests-oauthlib#223]
I am connecting to an API at api.sitescout.com, and I am able to authenticate and retrieve data successfully from my local machine. However, when I connect from my staging server, oauthlib seems to be changing the authorization header.

The log data follows, and I highlighted the changed header data in **bold**.

Is there something I need to do differently on my staging server to make this work properly?

02-05 17:24 requests_oauthlib.oauth2_session DEBUG    Requesting url https://api.sitescout.com/oauth/token using method POST.

02-05 17:24 requests_oauthlib.oauth2_session DEBUG    Supplying headers {'Host': 'api.sitescout.com', 'Content-Type': 'application/x-www-form-urlencoded', 'Accept': 'application/json', **'Authorization': 'Basic YmRubWFpbmZtYXBpOpopQio4VlMmPUsjbW8='**} and data {u'client_secret': u'mysecret', u'grant_type': u'client_credentials', u'params': u"{'grant_type': 'client_credentials'}"}

02-05 17:24 requests_oauthlib.oauth2_session DEBUG    Passing through key word arguments {'verify': True, 'json': None, 'timeout': None, 'auth': <requests.auth.HTTPBasicAuth object at 0x7f3af9fe7ed0>}.

02-05 17:24 requests.packages.urllib3.connectionpool INFO     Starting new HTTPS connection (1): api.sitescout.com

02-05 17:24 requests.packages.urllib3.connectionpool DEBUG    "POST /oauth/token HTTP/1.1" 401 26

02-05 17:24 requests_oauthlib.oauth2_session DEBUG    Prepared fetch token request body grant_type=client_credentials&params=%7B%27grant_type%27%3A+%27client_credentials%27%7D&client_secret=mysecret

02-05 17:24 requests_oauthlib.oauth2_session DEBUG    Request to fetch token completed with status 401.

02-05 17:24 requests_oauthlib.oauth2_session DEBUG    Request headers were {'Content-Length': '123', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'keep-alive', 'Accept': 'application/json', 'User-Agent': 'python-requests/2.7.0 CPython/2.7.6 Linux/3.13.0-48-generic', 'Host': 'api.sitescout.com', 'Content-Type': 'application/x-www-form-urlencoded', **'Authorization': 'Basic Tm9uZTpOb25l'**}

02-05 17:24 requests_oauthlib.oauth2_session DEBUG    Request body was client_secret=mysecret&grant_type=client_credentials&params=%7B%27grant_type%27%3A+%27client_credentials%27%7D

02-05 17:24 requests_oauthlib.oauth2_session DEBUG    Response headers were {'content-length': '26', 'server': 'AC1.1', 'cache-control': 'no-cache, no-store, must-revalidate', 'date': 'Fri, 05 Feb 2016 17:23:59 GMT', 'access-control-allow-origin': '*', 'content-type': 'application/json;charset=UTF-8', 'www-authenticate': 'Basic realm="SiteScout API"'} and content {"error":"invalid_client"}.

**Comment by jakeemerson** [comment]
Here is the code I am running.  Cheers!

`import os
import sys
import logging
import django
from django.core.management.base import BaseCommand
from oauthlib.oauth2 import BackendApplicationClient
from requests_oauthlib import OAuth2Session

from bdn_utils.centro import centro_config as config

try:
    from django.core.cache import caches
except django.core.exceptions.ImproperlyConfigured:
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "settings")
    django.setup()
    from django.core.cache import caches

# define the caches object
cache = caches['default']

logging.basicConfig(level=logging.DEBUG,
                    format='%(asctime)s %(name)-12s %(levelname)-8s %(message)s',
                    datefmt='%m-%d %H:%M',
                    filename='/var/log/boundary/requests_oauthlib.log')

log = logging.getLogger('requests-oauthlib')
log.addHandler(logging.StreamHandler(sys.stdout))
log.setLevel(logging.DEBUG)


class Command(BaseCommand):
    help = 'Grabs a new Oauth2 token from centro, and stores it in memcached.'

    def handle(self, *args, **options):
        """
        token returns an object like this:
        token = {'access_token': 'c525d0dacd38cafc8c7c52315655df66',
                 'scope': ['STATS', 'CONTROL', 'AUDIENCES'],
                 'token_type': 'bearer',
                 'expires_in': 3587,
             'expires_at': 1450724652.705038}
        """

        app_client = BackendApplicationClient(client_id=config.CLIENT_ID)

        headers = {
            "Host": "api.sitescout.com",
            "Authorization": "Basic YmRubWFpbmUtYXBpOmomQio4VlMmQUsjbW8=",
            "Content-Type": "application/x-www-form-urlencoded",
            "Accept": "application/json"
        }

        token_params = {"grant_type": "client_credentials"}

        client = OAuth2Session(client=app_client)

        token = client.fetch_token(token_url='https://api.sitescout.com/oauth/token',
                                   client_secret=config.CLIENT_SECRET,
                                   headers=headers,
                                   params=token_params)

        cache.set('centro_token', token)`

**Comment by Lukasa** [comment]
Sorry, I think this is a bug in the current release. Try using the code from the master branch to see if it is?

(NB: I believe this is a duplicate of #211).

**Comment by jakeemerson** [comment]
Yes, that solved it. Thank you so much for pointing out the solution @Lukasa.
