### ISSUE TITLE
windows live invalid client

### ISSUE THREAD

**Issue by underchemist** [requests/requests-oauthlib#225]
Hi,

I'm new to OAuth so I might be doing something entirely wrong. However I've been stuck with getting an invalid client error when using requests_oauthlib to request a token through microsoft live provider for OAuth2, however if I do it manually with get and post methods using just requests I am able to get an access token.

I tried to model my test after one of the examples on readthedocs. 

```
from requests_oauthlib import OAuth2Session

client_id = '000000004818699B'
client_secret = 'LCWGFSKre4EC0tvJ9Un2Zid03QCcUCnA'
authorization_base_url = 'https://login.live.com/oauth20_authorize.srf'
token_url = 'https://login.live.com/oauth20_token.srf'
redirect_url = 'https://localhost'
scope = ['wl.signin', 'xbox.basic', 'xbox.offline_access']

live = OAuth2Session(client_id=client_id, redirect_uri=redirect_url, scope=scope)

authorization_url, state = live.authorization_url(authorization_base_url)

redirect_response = input('go to {} and paste redirect url: '.format(authorization_url))

token = live.fetch_token(token_url, client_id=client_id, client_secret=client_secret, authorization_response=redirect_response, verify=False)

print(token)
```

but I get 

```
oauthlib.oauth2.rfc6749.errors.InvalidClientError: (invalid_client) The client does not exist. If you are the application developer, configure a new application through the application management site at https://manage.dev.live.com/.
```

However when I try just using requests,

```
import requests

client_id = '000000004818699B'
client_secret = 'LCWGFSKre4EC0tvJ9Un2Zid03QCcUCnA'
authorization_base_url = 'https://login.live.com/oauth20_authorize.srf'
token_url = 'https://login.live.com/oauth20_token.srf'
redirect_url = 'https://localhost'
scope = ['wl.signin', 'xbox.basic', 'xbox.offline_access']

r = requests.get(authorization_base_url + '?client_id=' + client_id + '&scope=wl.signin&response_type=code&redirect_uri=' + redirect_url)

authorization_url = r.url

code = input('go to {} and paste code portion: '.format(authorization_url))

r = requests.post(token_url, {'client_id': client_id, 'redirect_uri': redirect_url, 'client_secret': client_secret, 'code':code, 'grant_type': 'authorization_code'})

print(r.text)
```

I get a dictionary with my access token. 

Is there something in my implementation using oauthlib that I did wrong? or that is microsoft live specific?

I realize I'm giving my client secret away but once I get this working I will just create a new one.

Thanks for any of your help!

**Comment by Lukasa** [comment]
One thing to note is that your scopes aren't the same in both examples. Have you tried restricting to just scope `wl.signin` in the oauthlib example?

**Comment by underchemist** [comment]
I actually started with `wl.signin` when using oauthlib and added the others because I thought it might help. It had the same result.

Here's a full traceback if that's helpful

[traceback](http://pastebin.com/GMN5M4W5)

**Comment by underchemist** [comment]
Also I realize there is an insecure connection warning at the top, would that be something causing an issue? I don't get any warnings like that doing it manually with requests

**Comment by Lukasa** [comment]
The warning is caused by `verify=False`. Remove that to fix it. 

Out of interest, are you *absolutely sure* your client ID is right?

**Comment by underchemist** [comment]
yeah I'm about as sure as I can be with client id, I've used it successfully with requests and copy and pasted it multiple times from the app registration page.

**Comment by Lukasa** [comment]
You say you've used it successfully with requests: did you verify in the content that the token came back rather than an error?

**Comment by underchemist** [comment]
yes I did just double check and I get a proper token

**Comment by Lukasa** [comment]
Out of interest, can you try with the current `master` branch?

**Comment by underchemist** [comment]
interesting! 

I installed from master branch and it works. 

I installed it with

`pip install https://github.com/requests/requests-oauthlib/zipball/master`

I'm trying to diff the differences between them but you will probably be able to identify the differences. 

Is the current master branch not the current pip release?

**Comment by underchemist** [comment]
What I see are are some differences in oauth2_session.py between the two versions.

specifically in oauth2_session.py from pip
`auth = auth or requests.auth.HTTPBasicAuth(username, password)` 

is replaced in oauth2_session.py from current master branch as
```
if (not auth) and username:
            if password is None:
                raise ValueError('Username was supplied, but not password.')
            auth = requests.auth.HTTPBasicAuth(username, password)
```

**Comment by Lukasa** [comment]
The current one is not the pip release. =)

Yeah, you identified what I suspected was the problem. The current pip release has an issue around basic auth, and in particular in some flows will attach a basic auth header that decodes as username `None` and password `None`.

This'll be fixed when we next push a release. =) In the meantime, you can prototype with the code from master. =)

Sorry about the trouble!
