### ISSUE TITLE
InvalidClient: HTTPBasicAuth with username and password for Legacy Applications

### ISSUE THREAD

**Issue by synasius** [requests/requests-oauthlib#227]
I stumbled upon this error while trying to use requests-oauthlib with an oauth2 server created using django-oauth-toolkit. I think that there is a misunderstanding of section 2.3.1 of the RFC 6749 (here is the link https://tools.ietf.org/html/rfc6749#section-2.3.1) that is also the cause of #221 and #218 

The RFC says:
> Clients in possession of a client password MAY use the HTTP Basic
   authentication scheme as defined in [RFC2617] to authenticate with
   the authorization server.

The `client password` is the `client secret`. How should we create a Basic Auth Header? the RFC says:
> The *client identifier* is encoded using the
   "application/x-www-form-urlencoded" encoding algorithm per
   Appendix B, and the encoded value is used as the username; the *client
   password* is encoded using the same algorithm and used as the
   password.

client_id is used as username.
client_secret is used as password.

So I think that the header should be create as follows (and that is what we expect in django-oauth-toolkit):
```
auth = requests.auth.HTTPBasicAuth(client_id, client_secret)
```
the problem is that `username` and `password` are used instead, which are user's credentials and not the application's credentials.

Also, the RFC example shows the following header
> Authorization: Basic czZCaGRSa3F0Mzo3RmpmcDBaQnIxS3REUmJuZlZkbUl3

If you decode the base64 value you'll get:
```
>>> base64.b64decode('czZCaGRSa3F0Mzo3RmpmcDBaQnIxS3REUmJuZlZkbUl3')
>>> b's6BhdRkqt3:7Fjfp0ZBr1KtDRbnfVdmIw'
```
which are the client_id and client_secret  used in the example at the end of section 2.3.1

**Comment by synasius** [comment]
Forgot to mention that, if you agree with my analysis, I can submit a PR.

**Comment by Lukasa** [comment]
Reading the RFC appears to support your position, so I'm prepared to go with it. Feel free to submit a PR.

**Comment by poswald** [comment]
Added a PR as a proposed fix. Please let me know if you think it will cause issues for other grant types or if the logic is not ideal in any way.

**Comment by poswald** [comment]
This one can probably be closed too now that the PR is merged.
