### ISSUE TITLE
Client Authentication failed

### ISSUE THREAD

**Issue by djn40** [requests/requests-oauthlib#231]
Hi
I'm trying to connect to the paychoice api, which has a username and password for authentication.
If I use curl url -u user:password, it works fine, but trying BackendApplicationClient(client_id=client_id, client_secret=client_secret)
Fails.

Thanks.

**Comment by Lukasa** [comment]
@djn40 Can you try the code in the current master please?

**Comment by djn40** [comment]
Cloned https://github.com/requests/requests-oauthlib.git
Ran setup.py install.
Still doesn't work, same error.

I can use curl with -u user:pw option, but this library isn't working at
all.

Thanks.

**Comment by Lukasa** [comment]
So to be clear, curl -u username:password is not the same as oauthlib: you can get that effect with standard requests (`requests.get(url, auth=(username, password))`). Is that what you were looking for?
