### ISSUE TITLE
OAuth2Session(client_id=client_id, client=client) return 403 error in production environment

### ISSUE THREAD

**Issue by ilGuccio** [requests/requests-oauthlib#232]
OAuth2Session(client_id=client_id, client=client) return 403 error in production environment.
Works good in localhost

In localhost and production environment I disabled OAUTHLIB_INSECURE_TRANSPORT
`os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'`

**Comment by ilGuccio** [comment]
OAuth2Session(client_id=client_id, client=client, token=token).get(URL)

**Comment by Lukasa** [comment]
Are you sure your client id and token are valid for the production environment?

**Comment by ilGuccio** [comment]
Sure, I'm trying to use it for test my rest service. When I run it in localhost, it works good. In production, in virtual machine I obtain 403 error on my requests, the only difference is the environment.
If i use django.test.client requests work, even in production.

**Comment by Lukasa** [comment]
Does your use of the django test client actually do the OAuth dance?

**Comment by ilGuccio** [comment]
Yes. Btw in my rest service  implement only the client credential flow

**Comment by Lukasa** [comment]
So you're using the `BackendApplicationClient`? Is it appropriately configured?

Are there any backend differences between you running against localhost and running in production? Can you find any reason for the 403 in the logs?

**Comment by ilGuccio** [comment]
Nothing in log, but my code
```
def get(self, request):
        operation = request.GET['operation']
        client_id = request.GET['client_id']
        secret = request.GET['client_secret']
        word = request.GET['word']
        word_type = request.GET['type']
        client = BackendApplicationClient(client_id=client_id)
        oauth = OAuth2Session(client=client, scope=['read', 'write'])
        import os
        os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'
        try:
            token = request.session['oauth_token' + client_id]
            oauth = OAuth2Session(client=client, token=token, scope=['read', 'write'])
        except KeyError:
            oauth = OAuth2Session(client=client, scope=['read', 'write'])
            token = oauth.fetch_token(token_url="http://" + request.get_host() + '/o/token/', client_id=client_id, client_secret=secret)
            request.session['oauth_token' + client_id] = token
        try:
            if settings.DEBUG is True:
                url = "http://" + request.get_host() + self.apiUrls[
                    str(operation)] + "?word=" + word + "&type=" + word_type                
            else:
                url = "https://" + request.get_host() + self.apiUrls[
                    str(operation)] + "?word=" + word + "&type=" + word_type
            r = oauth.get(url)
        except TokenExpiredError:
            oauth = OAuth2Session(client_id=client_id, client=client)
            token = oauth.fetch_token(token_url="http://" + request.get_host() + '/o/token/', client_id=client_id, client_secret=secret)
            request.session['oauth_token' + client_id] = token            
            if settings.DEBUG is True:
                url = "http://" + request.get_host() + self.apiUrls[
                    str(operation)] + "?word=" + word + "&type=" + word_type
            else:
                url = "https://" + request.get_host() + self.apiUrls[
                    str(operation)] + "?word=" + word + "&type=" + word_type
            r = oauth.get(url)      
        if r.status_code == 403:
            del request.session['oauth_token' + client_id]
            return HttpResponseForbidden()
        return JsonResponse(r.content, safe=False)
```

**Comment by Lukasa** [comment]
I'd be very interested to know whether the control flow through this function is the same in both your localhost and production instances. Are you going to be able to safely discover that on your production deployment?

**Comment by ilGuccio** [comment]
How could it be different? I'm running in debug mode even the production

**Comment by Lukasa** [comment]
@ilGuccio The function is complex enough and depends enough on external factors that it *could* be different. I'd like to rule that possibility out first. When debugging, simply *assuming* that the code is functioning as you expect is not good enough. We must prove it. =)

**Comment by ilGuccio** [comment]
I'm truly confused, tryed to run the application on virtual machine via `python manage.py runserver 0.0.0.0:8000` and access it by its public ip and it works :/

**Comment by Lukasa** [comment]
This is why I want you to trace the flow of execution: I don't think we know what's going on here.

**Comment by ilGuccio** [comment]
Solved, the problem was Apache configuratio
http://www.django-rest-framework.org/api-guide/authentication/#apache-mod_wsgi-specific-configuration
Need to set `WSGIPassAuthorization On`

**Comment by Lukasa** [comment]
Aha, thanks for following up! :sparkles:
