### ISSUE TITLE
Is requests-oauthlib compatible with Python 3?

### ISSUE THREAD

**Issue by cclauss** [requests/requests-oauthlib#239]
The README.rst does not mention Python versions and PyPI record (https://pypi.python.org/pypi/requests-oauthlib) does not contains neither Python 2 nor a Python 3 classifier text.

**Comment by cclauss** [comment]
https://github.com/requests/requests-oauthlib/blob/master/setup.py#L61mentions Python3 support but the PyPI record (https://pypi.python.org/pypi/requests-oauthlib) does not contain these classifiers.

**Comment by Lukasa** [comment]
Apologies, the trove classifiers have been uploaded to PyPI now.
