### ISSUE TITLE
Can't override/suppress Authentication and User-Agent headers

### ISSUE THREAD

**Issue by RobWilco** [requests/requests-oauthlib#245]
Using a grant type of `password`, the OAuth2 provider I'm calling doesn't like when the `Authentication` header (and possibly `User-Agent` header) is included. When I remove them, all is well. Not seeing a way to suppress them as of yet. Thoughts?

**Comment by Lukasa** [comment]
In the first instance I should note that your OAuth2 provider needs to be better. The OAuth2 spec requires that clients be able to do this.

Regardless, you can suppress those the Authorization field by setting `auth=False`.

**Comment by Lukasa** [comment]
Note that, currently, you'll need to use the master branch for that.
