### ISSUE TITLE
0.7.0 regression related to passing auth= parameter

### ISSUE THREAD

**Issue by eranrund** [requests/requests-oauthlib#254]
Hello :)
0.7.0 introduced this commit: https://github.com/requests/requests-oauthlib/commit/33483808497c8a993dfd388a1a4b11849b487318 which introduces a problem if `kwargs` contains `auth`.

For example, the Asana python library does this: ` response = getattr(self.session, method)(url, auth=self.auth, **request_options)`
https://github.com/Asana/python-asana/blob/master/asana/client.py#L73

The stack trace this results in looks like this:
```
TypeError: refresh_token() got multiple values for keyword argument 'auth'
[... stripped internal code... ]
  File "asana/resources/gen/tasks.py", line 25, in create
    return self.client.post("/tasks", params, **options)
  File "asana/client.py", line 124, in post
    return self.request('post', path, data=body, headers={'content-type': 'application/json'}, **options)
  File "asana/client.py", line 74, in request
    response = getattr(self.session, method)(url, auth=self.auth, **request_options)
  File "requests/sessions.py", line 518, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "requests_oauthlib/oauth2_session.py", line 341, in request
    self.auto_refresh_url, auth=auth, **kwargs
```

I'm assuming it is acceptable to pass an `auth` parameter. If not, I'll discuss this with the Asana people.

Thanks <3

**Comment by Lukasa** [comment]
Yeah, this code should probably be more defensive against users passing in `auth` values from above. @singingwolfboy are you interested in correcting this regression?

**Comment by eranrund** [comment]
Thanks :)
