### ISSUE TITLE
__version__ naming conflict

### ISSUE THREAD

**Issue by JherezTaylor** [requests/requests-oauthlib#281]
The version [check](https://github.com/requests/requests-oauthlib/blob/master/requests_oauthlib/__init__.py#L8) in `requests_oauthlib/__init__.py` throws the following error under Python 3.5.3:
`unorderable types: module() < str()`

When I print the value of `requests.__version__` it prints the path of the module `requests.__version__` rather than the current package value `2.17.3`

**Comment by Lukasa** [comment]
Ugh, this seems like a breaking change in Requests 2.17.3. Let's see if we can clean that up.

**Comment by JherezTaylor** [comment]
Yea, I noticed it through a Twython import.

**Comment by Lukasa** [comment]
Hrm, hang on, what platform are you running on? I can't reproduce this problem with Requests directly in a shell.

**Comment by JherezTaylor** [comment]
Ubuntu: 17.04
Python: 3.5.3
Jupyter Notebook: 4.4.0

Is there any other debug info I can provide?

**Comment by Lukasa** [comment]
Hrm, that's very odd. For this to be the case there would need to be some indeterminacy in the way things end up in the namespace. The way the Requests imports are written this should not be happening. Are you 100% confident that version 2.17.3 of Requests is what's running in your Jupyter kernel?

**Comment by JherezTaylor** [comment]
Attaching the following screenshots and my stack trace
[trace.txt](https://github.com/requests/requests-oauthlib/files/1045052/trace.txt)
![version_check1](https://cloud.githubusercontent.com/assets/8041270/26684324/37d291d4-4719-11e7-8964-e361a2f0c7f9.png)
![version_check2](https://cloud.githubusercontent.com/assets/8041270/26684327/399cf0c2-4719-11e7-845a-45268d3386a4.png)

**Comment by JherezTaylor** [comment]
I should note that I can't seem to replicate the issue by creating a notebook that only includes the requests and requests_oauthlib import. I suspect that there might be some other funny business going on that doesn't involve requests_ouathlib. I'll just monkey patch it locally and go about my business.

**Comment by Lukasa** [comment]
Yeah, this seems to be a weirdness in your system somewhere. Sorry we can't be of more help!
