### ISSUE TITLE
fetch_token doesnt pass scope to oauthlib

### ISSUE THREAD

**Issue by pm100** [requests/requests-oauthlib#285]
SO if I am doing a BackendApplicationClient app that needs to pass a scope it doesn't work

```
def getToken(client_id,client_secret,url):
    client = BackendApplicationClient(client_id=client_id)
    oauth = OAuth2Session(client=client, scope = ['myscope'])
    token = oauth.fetch_token(token_url=url, client_id=client_id,   client_secret=client_secret)
```

the request that gets sent doesn't pass scope through

**Comment by Lukasa** [comment]
There's an outstanding pull request for this at #283. If you'd like to resurrect it, you may. :smile:

**Comment by pm100** [comment]
i am not github savvy at all so dont know what that means. I have fixed the code (a trivial fix add: scope = self.scope to arg list of prepare_request_body call)

**Comment by Lukasa** [comment]
All it means is that the patch needs to be extended. This might be a great time to learn to use GitHub!
