### ISSUE TITLE
security vulnerability report

### ISSUE THREAD

**Issue by YangRonghai** [requests/requests-oauthlib#291]
I have discovered some security vulnerabilities. I tried to reach the development lead Kenneth Reitz <me@kennethreitz.com> (as shown in the AUTHORS.rst), but did not get reply. So who can I reach  to privately report the vulnerability?

**Comment by nateprewitt** [comment]
@YangRonghai, you can contact any of the other maintainers (@Lukasa, @sigmavirus24 or myself) and we'd be happy to review what you've found. We all have our emails listed on our profiles. Thanks for letting us know!

**Comment by singingwolfboy** [comment]
Hopefully, @YangRonghai followed up privately with one of the maintainers. Since there doesn't seem to be anything more to say on this public GitHub issue, I'm going to close it.
