### ISSUE TITLE
Facebook OAuth flow no longer working

### ISSUE THREAD

**Issue by bhargavrpatel** [requests/requests-oauthlib#301]
Hello,

We had a working implementation which used the wonderful requests-oauthlib with Facebook. The code was no different than the sample code in the documentation. Suddenly, it just stopped working. When we visit the generated URL, we see the following: 
![image](https://user-images.githubusercontent.com/911413/33956021-6032e224-e00b-11e7-9a2f-2872fe2e8464.png)

The generated url where XXXXX represent the client specific details.
```
https://www.facebook.com/v2.10/dialog/oauth?response_type=code&client_id=XXXXX
&redirect_uri=https%3A%2F%2FXXXXX
&scope=id+name+first_name+last_name+email
&state=XXXXX&timeout=60
```

Anyone else experiencing this? Can one of the devs please validate that it is working? We'd really appreciate it.

Thanks!

**Comment by bhargavrpatel** [comment]
Update: Have narrowed it down to scope parameter being present in the URL.

**Comment by umgelurgel** [comment]
Were you able to resolve this issue and get the library to work with Facebook Oauth? I see that this request works without the scope, but the `OAuth2Session.fetch_token` seems to be consistently failing with a `MissingTokenError` exception.

**Comment by singingwolfboy** [comment]
@bhargavrpatel: are you still having this problem? If so, can you provide a minimal reproducible test case? That would help with debugging the issue and fixing it.
