### ISSUE TITLE
No modulenames 'requests_oauthlib'

### ISSUE THREAD

**Issue by YODAWGAADADWA** [requests/requests-oauthlib#304]
from requests_oauthlib import OAuth2Session 

`ModuleNotFoundError: No module named 'requests_oauthlib`

I am using windows 64 bit python 32 bit. 

Any idea why this is happening?This is installed as per:

`C:\Users\Chea\zz>pip install requests requests_oauthlib Requirement already satisfied: requests in c:\users\Chea\appdata\local\programs\python\python36-32\lib\site-packages Requirement already satisfied: requests_oauthlib in c:\users\Chea\appdata\local\programs\python\python36-32\lib\site-packages Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\users\Chea\appdata\local\programs\python\python36-32\lib\site-packages (from requests) Requirement already satisfied: certifi>=2017.4.17 in c:\users\Chea\appdata\local\programs\python\python36-32\lib\site-packages (from requests) Requirement already satisfied: idna<2.7,>=2.5 in c:\users\Chea\appdata\local\programs\python\python36-32\lib\site-packages (from requests) Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\Chea\appdata\local\programs\python\python36-32\lib\site-packages (from requests) Requirement already satisfied: oauthlib>=0.6.2 in c:\users\Chea\appdata\local\programs\python\python36-32\lib\site-packages (from requests_oauthlib)`

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
