### ISSUE TITLE
Error when using from python3

### ISSUE THREAD

**Issue by muhsinalungal** [requests/requests-oauthlib#338]
Please look into the following Screenshot, I am getting the error from the basic library itself.

from requests_oauthlib import OAuth1Session
  File "/home/cintanalap6u/.local/lib/python3.6/site-packages/requests_oauthlib/__init__.py", line 11, in <module>
    if requests.__version__ < '2.0.0':
TypeError: '<' not supported between instances of 'module' and 'str'

**Comment by skriems** [comment]
I just created a new env with py36 and `python -c "from requests_oauthlib import OAuth1Session"` works fine.
Also there's no `.../requests_oauthlib/init.py` - it should be `__init__.py`.

**Comment by NNTin** [comment]
If anyone comes across this error, upgrade your pip to latest version. That will fix the error.

Reproduction:  
get pip 9.0.1 (released in Nov 2016, Some distro still bundle it.)    

I don't know in which pip version this was fixed.

```py
import pip
from requests_oauthlib import OAuth1Session
```
