### ISSUE TITLE
oauthlib-3.0.0 is released

### ISSUE THREAD

**Issue by prometheanfire** [requests/requests-oauthlib#356]
requests-oauthlib is incompatible.  Mind raising the limit (if tests pass) and making a new release (1.1.1 at this point)?

oauthlib[signedtoken]>=2.1.0,<3.0.0

https://github.com/requests/requests-oauthlib/commit/1b9fe1a630eb1c91bf12fd70aa2e10ca74ffc0b6

**Comment by singingwolfboy** [comment]
@prometheanfire I don't understand. requests-oauthlib version 1.1.0 was released yesterday, specifically to address this issue. Does requests-oauthlib version 1.1.0 try to use oauthlib version 3.0.0?

**Comment by prometheanfire** [comment]
No, the issue is that I can't use oauthlib-3.0.0 with requests-oauthlib-1.1.0.  I am requesting raising the cap on oauthlib if tests pass.

http://logs.openstack.org/72/629772/2/check/requirements-tox-py27-check-uc/7335eea/job-output.txt.gz#_2019-01-10_08_06_07_978267

As it is, I'm holding back new versions of requests-oauthlib until they are co-installable.

https://review.openstack.org/629772

**Comment by ryanhiebert** [comment]
I just did a little digging to understand the current state of affairs. Here's my conclusions.

The dependency version change was done at the request of the oauthlib maintainers in #341. That was done to better handle the transition of #331, which applies the new changes from oauthlib 3.0.

**Comment by prometheanfire** [comment]
thanks, watching #357 now
