### ISSUE TITLE
Async alternative 

### ISSUE THREAD

**Issue by tetienne** [requests/requests-oauthlib#365]
Hi, and sorry for this non issue ticket. I want to update my module to be async compliant. Do you know if async alternative to this library exist. If yes, can you redirect me to it?

**Comment by lepture** [comment]
@tetienne I just started my implementation for aiohttp based on [Authlib](https://github.com/lepture/authlib).

I just released the first preview version. It still requires some time of work to get the documentation and tests done. Check it out at: https://github.com/authlib/aiohttp-oauth-client

**Comment by tetienne** [comment]
@lepture many thanks, it will be a really great library.

**Comment by lepture** [comment]
@tetienne Oh, better with HTTPX: https://docs.authlib.org/en/latest/client/httpx.html

But, please use HTTPX < 0.8.

**Comment by murata100** [comment]
I found [Async-OAuthlib](https://pypi.org/project/Async-OAuthlib/).
requests-oauthlib -like interface.
