### ISSUE TITLE
Read the Docs is out of sync.

### ISSUE THREAD

**Issue by waiterw** [requests/requests-oauthlib#392]
As one example, I found difference between
https://github.com/requests/requests-oauthlib/blob/master/requests_oauthlib/oauth2_session.py
and
https://requests-oauthlib.readthedocs.io/en/latest/api.html#oauth-2-0
.

**Comment by JonathanHuot** [comment]
The project is missing maintainers, and the issue requires to properly build  & make releases of the project regularly by active maintainers.

See https://github.com/requests/requests-oauthlib/issues/385 to add your support.

**Comment by JonathanHuot** [comment]
Blocked by error from ReadTheDocs as described at https://readthedocs.org/projects/requests-oauthlib/builds/15158021/

```
  File "/home/docs/checkouts/readthedocs.org/user_builds/requests-oauthlib/envs/stable/lib/python2.7/site-packages/sphinx/util/nodes.py", line 94, in apply_source_workaround
    for classifier in reversed(node.parent.traverse(nodes.classifier)):
TypeError: argument to reversed() must be a sequence

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/requests-oauthlib/envs/stable/lib/python2.7/site-packages/sphinx/util/nodes.py", line 94, in apply_source_workaround
    for classifier in reversed(node.parent.traverse(nodes.classifier)):
TypeError: argument to reversed() must be a sequence
```

**Comment by JonathanHuot** [comment]
This is now fixed in latest version of RTD.
