### ISSUE TITLE
Docs revision is outdated (at f8e741dc)

### ISSUE THREAD

**Issue by mig4ng** [requests/requests-oauthlib#418]
The docs are outdated in a old revision (commit f8e741dc from Jul 25, 2018).

E.g.:
https://requests-oauthlib.readthedocs.io/en/latest/oauth2_workflow.html#backend-application-flow is missing `>>> from requests_oauthlib import OAuth2Session` in step 1 compared to https://github.com/requests/requests-oauthlib/blob/master/docs/oauth2_workflow.rst#id12

I was going to create a pull request fixing this yet I got confused that in the file it was fixed already 😅

Is there a reason for this or is it a bug?

Cheers!

**Comment by jtroussard** [comment]
I'm not 100% on this but I believe an official release needs to be released before the docs are rebuilt/sync'ed.

**Comment by JonathanHuot** [comment]
ReadTheDocs built has been fixed. It was somehow stuck since long time, but finally has been restored. 
Two last versions are activated 1.3.0 and 1.3.1.
