### ISSUE TITLE
Consider adding new hooks - request_access_token and request_refresh_token

### ISSUE THREAD

**Issue by viperfx** [requests/requests-oauthlib#420]
These hooks are implemented right before the request is sent for the fetch token and similar for the refresh token request too. 

These hooks are required for me to apply a compliance fix for Azure Devops

https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/oauth?view=azure-devops

**Comment by jtroussard** [comment]
Please feel free to raise a PR with these changes and unit tests.

**Comment by violuke** [comment]
This should be possible now, see #433
