### ISSUE TITLE
When will the next version be released ?

### ISSUE THREAD

**Issue by Exchizz** [requests/requests-oauthlib#426]
Hi,
When will the next version of requests-oauthlib implementing Mutal TLS be released ?   
Mutal TLS is implemented in https://github.com/requests/requests-oauthlib/commit/ae5c81d52457271d8f93d34c3c42d43f15ca2c69 but does not seem to be included in the latest release on pypip (1.3.0).

Thanks in advance :+1:

**Comment by JonathanHuot** [comment]
1.3.1 has been released.
