### ISSUE TITLE
Update pipeline/Github actions

### ISSUE THREAD

**Issue by jtroussard** [requests/requests-oauthlib#460]
Seems the coverage report and tests are not kicking off. Would like to update/fix this as part of the [1.3.1](https://github.com/requests/requests-oauthlib/milestone/3) milestone.

**Comment by JonathanHuot** [comment]
I would consider this work as critical as it will help other PRs to be merged into master.

**Comment by jtroussard** [comment]
@JonathanHuot Looks like the coveralls and branch protection features are running. I know we had a bit of a discussion about the way the coverall coverages were being calculated but can we confirm were we wanted to cut a release? Do we want to wait for a more substantial test of the branch protection features/coveralls coverage check? Do we want to include the documentation reformat/update into this milestone?

**Comment by jtroussard** [comment]
@JonathanHuot Looks like 1.3.1 is wrapping up nicely. Are we ready to cut a release?

**Comment by JonathanHuot** [comment]
@jtroussard , yes let's cut the release!
