### ISSUE TITLE
coveralls decreased coverage threshold too thin

### ISSUE THREAD

**Issue by jtroussard** [requests/requests-oauthlib#477]
@JonathanHuot I believe you have permission to update coverall settings?

Looks like we should add a threshold value for decreased value to all for code reduction. Removing basically anything from the code base, seemingly even just comments (see #476 ) results in the remaining code to carry a slightly heavier weight. At least this is what I think is happening when coveralls runs it 3.8/3.9 coverage checks. It is failing simple, non-functional changes. Can we increase the decreased coverage threshold to something arbitrarily small? 0.1? Or perhaps there is a work around for this? Is there a coverall setting to ignore comments?

**Comment by JonathanHuot** [comment]
Coverage threshold has been set to 1% to avoid having floating or adding comment problems.
