### ISSUE TITLE
1.3.2 release?

### ISSUE THREAD

**Issue by andrewlytleawn** [requests/requests-oauthlib#520]
Hey, is there a timeline for release 1.3.2? There are some fixes in there we would like.

Appreciate it!

**Comment by violuke** [comment]
@JonathanHuot would it be possible to get a PyPI release, please? I'm really looking forward to #433 😉

**Comment by jtroussard** [comment]
@JonathanHuot I'll have some time the weekend of the 22nd if you want to pair up on this release.
