### ISSUE TITLE
Allow insecure communication for development

### ISSUE THREAD

**Issue by jcassee** [requests/requests-oauthlib#61]
OAuth2 requires a secure communication channel, i.e. HTTPS, and the library refuses connections on HTTPS. This is inconvenient when developing OAuth2-based applications. Setting up HTTPS locally is quite some work, especially with clients that verify the certificate chain.

Would you accept a pull request that adds an option to disable the HTTPS check?

Or alternatively, is there another way for requests-oauthlib to address this issue that I could implement?

**Comment by scott2b** [comment]
I don't see it stated in this thread -- the thread is probably older than the solution, but the fix seems to be to set the environment variable: `OAUTHLIB_INSECURE_TRANSPORT=1`
